- name: mysql configuration
  hosts: mysql
  become: yes
  tasks:
  - name: install MySQL Server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start mysql servers
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
